hand_description:
  right_arm:
    hand_frame: forearm_motor
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: r_gripper_r_finger_tip_link
    hand_group_name: r_end_effector
    arm_group_name: right_arm
    hand_database_name: WILLOW_GRIPPER_2010
    hand_joints: [r_gripper_l_finger_joint,r_gripper_r_finger_joint,r_gripper_r_finger_tip_joint,r_gripper_l_finger_tip_joint]
    hand_touch_links: [r_gripper_palm_link,r_gripper_r_finger_tip_link,r_gripper_l_finger_tip_link,r_gripper_l_finger_link,r_gripper_r_finger_link]
    hand_fingertip_links: [r_gripper_r_finger_tip_link,r_gripper_l_finger_tip_link]
    hand_approach_direction: [1.0,0.0,0.0]