## This file should be loaded under <robot description>_planning

## the definition of each group
groups:

  - name: right_arm
    joints:
      trunk_rotation
      shoulder_rotation
      elbow_abduction
      forearm_rotation
    links: 
      shadowarm_base
      shadowarm_trunk
      shadowarm_upperarm
      shadowarm_lowerarm
      shadowarm_handsupport_motor
  - name: arms
    joints: 
      trunk_rotation
      shoulder_rotation
      elbow_abduction
      forearm_rotation
    links:
      shadowarm_base
      shadowarm_trunk
      shadowarm_upperarm
      shadowarm_lowerarm
      shadowarm_handsupport_motor
    planner_configs:
      RRTkConfig2 SBLkConfig2 

  - name: r_end_effector
    links: 
      forearm_motor
      wrist
      palm
      ffknuckle
      ffproximal
      ffmiddle
      ffdistal
      mfknuckle
      mfproximal
      mfmiddle
      mfdistal
      rfknuckle
      rfproximal
      rfmiddle
      rfdistal
      lfmetacarpal
      lfknuckle
      lfproximal
      lfmiddle
      lfdistal
      thbase
      thproximal
      thhub
      thmiddle
      thdistal

