##
# This file contains the calibration map for the hand.
#
# The format is the following:
# [[joint_name, [ [raw_value, calibrated_value],
#                 [raw_value, calibrated_value],
#                 [...] ] ]]
##

sr_calibrations: [
  ["FFJ1", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #FFJ1
  ["FFJ2", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #FFJ2
  ["FFJ3", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #FFJ3
  ["FFJ4", [ [0.0, -0.4],
             [1.0,  0.4] ]],   #FFJ4

  ["MFJ1", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #MFJ1
  ["MFJ2", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #MFJ2
  ["MFJ3", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #MFJ3
  ["MFJ4", [ [0.0, -0.4],
             [1.0,  0.4] ]],   #MFJ4

  ["RFJ1", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #RFJ1
  ["RFJ2", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #RFJ2
  ["RFJ3", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #RFJ3
  ["RFJ4", [ [0.0,  0.0],
             [1.0,  0.0] ]],   #RFJ4

  ["LFJ1", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #LFJ1
  ["LFJ2", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #LFJ2
  ["LFJ3", [ [2000.0,  0.0],
             [3400.0, 1.57] ]],   #LFJ3
  ["LFJ4", [ [2000.0,  -0.4],
             [3300.0,  0.4] ]],   #LFJ4
  ["LFJ5", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #LFJ5


  ["THJ1", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #THJ1
  ["THJ2", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #THJ2
  ["THJ3", [ [0.0,  0.0],
             [1.0, 0.0] ]],   #THJ3
  ["THJ4", [ [0.0,  0.0],
             [1.0,  0.0] ]],   #THJ4
  ["THJ5", [ [0.0,  0.0],
             [1.0,  0.0] ]],   #THJ5

  ["WRJ1", [ [0.0, 0.],
             [1.0,  0.] ]],    #WRJ1
  ["WRJ2", [ [0.0, 0.],
             [1.0,  0.] ]]     #WRJ2
]
