##
# This is the mapping from joint to motor index

joint_to_motor_mapping: [
        0,      #FFJ0
        -1,     #FFJ1
        -1,     #FFJ2
        10,      #FFJ3
        11,      #FFJ4

        3,      #MFJ0
        -1,     #MFJ1
        -1,     #MFJ2
        4,      #MFJ3
        5,      #MFJ4

        9,      #RFJ0
        -1,     #RFJ1
        -1,     #RFJ2
        7,      #RFJ3
        8,      #RFJ4

        2,      #LFJ0
        -1,     #LFJ1
        -1,     #LFJ2
        6,     #LFJ3
        1,     #LFJ4
        12,     #LFJ4

        13,     #THJ1
        14,     #THJ2
        15,     #THJ3
        16,     #THJ4
        17,     #THJ5

        18,     #WRJ1
        19,     #WRJ2
]
