motor_data_update_rate: {
  sgl: -1.,
  sgr: -1.,
  pwm: -1.,
  flags: -1,
  current: -1,
  voltage: 1.,
  temperature: 1.,
  can_num_received: -1,
  can_num_transmitted: -1,
  svn_revision: 1.,
  f_p: 1.,
  i_d: 1.,
  imax_deadband_sign: 1.
  }
