motor_data_update_rate: {
  sgl: -1.,
  sgr: -1.,
  pwm: -1.,
  flags: -1,
  current: -1,
  voltage: 1.,
  temperature: 1.,
  can_num_received: -1,
  can_num_transmitted: -1,
  slow_data: 1.,
  can_error_counters: -1,
  pterm: -1.,
  iterm: -1.,
  dterm: -1.
  }
